version: 2.1

orbs:
  cfa: continuousauth/npm@2.1.0
  node: electronjs/node@2.2.2

workflows:
  test_and_release:
    jobs:
      - node/test:
          executor: node/linux
          name: test
          node-version: "18.20"
          test-steps:
            - run: yarn build
            - run: yarn test
          use-test-steps: true
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release
