version: 2.1
orbs:
  cfa: continuousauth/npm@2.1.0
jobs:
  test:
    docker:
      - image: cimg/node:16.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - cfa/release:
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context: cfa-release
